id = "zomorrod-theme"
name = "Zomorrod"
version = "0.0.1"
schema_version = 1
authors = ["Ali Nayreez alinayreez@gmail.com"]
description = "A visually appealing cool theme"
repository = "https://github.com/AliNayreez/zomorrod-theme"
